Added gyro and accelerometer
nullkal/UniSense pull request #1
Opened 2020-12-30 04:35 UTC by prnthp

At first I tried using VC3S as the format and a Vector3 as a type for the gyro and accelerometer axes, but Unity seems to be marshaling them improperly (there needs to be an intermediate short -> float first, I think).

Awesome work on this, btw! Thank you!

Hope this helps!

2020-12-30 17:04 UTC, nullkal requested changes
Thank you for sending the PR!
I tested your changes in my environment, and it seems it works without problem.

I have a suggestion regarding this PR, so please review it.

2020-12-30 17:04 UTC, nullkal commented on Assets/UniSense/LowLevel/DualSenseHIDInputReport.cs
> +        public short accelZ;
After I saw this PR, I tried to change your code to use VC3S.
I think it works properly in my environment.
How about this:

```suggestion
        [InputControl(name = "gyro", format = "VC2S", layout = "Vector3")]
        [InputControl(name = "gyro/x", layout = "Axis", format = "SHRT")]
        [InputControl(name = "gyro/y", offset = 2, layout = "Axis", format = "SHRT")]
        [InputControl(name = "gyro/z", offset = 4, layout = "Axis", format = "SHRT")]
        [FieldOffset(16)] public short gyroPitch;
        [FieldOffset(18)] public short gyroYaw;
        [FieldOffset(20)] public short gyroRoll;
    
        [InputControl(name = "accel", format = "VC2S", layout = "Vector3")]
        [InputControl(name = "accel/x", layout = "Axis", format = "SHRT")]
        [InputControl(name = "accel/y", offset = 2, layout = "Axis", format = "SHRT")]
        [InputControl(name = "accel/z", offset = 4, layout = "Axis", format = "SHRT")]
        [FieldOffset(22)] public short accelX;
        [FieldOffset(24)] public short accelY;
        [FieldOffset(26)] public short accelZ;
```

2020-12-30 18:26 UTC, prnthp commented
Sweet! That works!

2020-12-31 04:00 UTC, nullkal approved these changes

2020-12-31 04:01 UTC, merged